# Generated by Django 4.2.6 on 2023-12-06 03:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('PG', 'No pagado'), ('PD', 'Pendiente'), ('EN', 'Enviado'), ('RC', 'Recibido')], default='PG', max_length=2)),
                ('fecha_inicio', models.DateTimeField()),
                ('fecha_completada', models.DateTimeField()),
                ('direccion', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40)),
                ('precio_unico', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('precio_mediana', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('precio_familiar', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('ingredientes', models.CharField(max_length=200)),
                ('disponible', models.BooleanField(default=True)),
                ('tipo', models.CharField(choices=[('OMN', 'Omnívora'), ('VGT', 'Vegetariana'), ('VGN', 'Vegana'), ('ACO', 'Acompañamiento')], default='OMN', max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='FragmentoPedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField()),
                ('precio_total', models.DecimalField(decimal_places=2, max_digits=20)),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apphost.pedido')),
                ('producto', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='apphost.producto')),
            ],
        ),
    ]
