# Generated by Django 4.2.6 on 2023-12-06 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apphost', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='fecha_completada',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='fecha_inicio',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
