# Generated by Django 4.2.6 on 2023-12-06 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apphost', '0002_alter_pedido_fecha_completada_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='estado',
            field=models.CharField(choices=[('PG', 'No pagado'), ('PD', 'Pendiente'), ('EN', 'Enviado'), ('RC', 'Recibido'), ('CN', 'Cancelado')], default='PG', max_length=2),
        ),
    ]
