# Generated by Django 4.2.6 on 2023-12-11 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apphost', '0004_fragmentopedido_tamano_alter_pedido_estado'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trabajador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut', models.IntegerField(unique=True)),
                ('password', models.CharField(max_length=30)),
            ],
        ),
        migrations.AlterField(
            model_name='pedido',
            name='estado',
            field=models.CharField(choices=[('PG', 'No pagado'), ('PD', 'Pendiente'), ('EN', 'Enviado'), ('RC', 'Recibido'), ('CN', 'Cancelado')], default='PD', max_length=2),
        ),
    ]
